apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    qingyuanos.com/catalog-by: '{"version": "v1alpha", "lib": "https://github.com/qingyuancloud/harpoon", "documentation": "https://github.com/kubernetes/kubernetes/tree/master/examples/rbd"}'
  labels:
    app: mysql-galera
    heritage: qingyuancloud
    name: mysql-galera-ceph-rbd
    project: openshift.org
  name: galera-rbd-pvc3
spec:
  accessModes:
  - ReadOnlyMany
  - ReadWriteMany
  - ReadWriteOnce
  resources:
    limits:
      storage: 5Gi
    requests:
      storage: 500Mi
  volumeName: galera-rbd-pv3
