---
apiVersion: v1
kind: Service
metadata:
  lables:
    name: mysql-galera-ceph-secret
  name: mysql-galera-ceph-secret
spec:
  clusterIP: "None"
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  - port: 4444
    targetPort: 4444 
    name: state-snapshot-transfer
  - port: 4567
    targetPort: 4567
    name: replication-traffic 
  - port: 4568
    targetPort: 4568 
    name: incremental-state-transfer 
  selector:
    app: mysql-galera-ceph-secret
